=== MoDReD/Packet-Samurai-Versions/Packet Samurai 5.x/protocols/protocol.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="protocol">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element maxOccurs="unbounded" name="bitset" type="BitSet" />
          <xs:element maxOccurs="unbounded" name="multivalue" type="MultiValue" />
          <xs:element name="packetfamilly" type="PacketFamily" />
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="crypt" type="xs:string" use="required" />
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="port" type="xs:unsignedShort" use="required" />
      <xs:attribute name="checksumSize" type="xs:unsignedByte" use="required" />
      <xs:attribute name="strictlength" type="xs:boolean" use="optional" />
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Part">
    <xs:sequence minOccurs="0">
      <xs:element name="reader" type="Reader" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="type" type="xs:string" use="required" />
    <xs:attribute name="id" type="xs:string" use="optional" />
    <xs:attribute name="size" type="xs:unsignedInt" use="optional" />
    <xs:attribute name="sizeid" type="xs:unsignedByte" use="optional" />
  </xs:complexType>
  <xs:complexType name="Reader">
    <xs:attribute name="type" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="real" type="xs:boolean" use="optional" />
    <xs:attribute name="url" type="xs:anyURI" />
  </xs:complexType>
  <xs:complexType name="Switch">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="case" type="Flow" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="Flow">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" name="part" type="Part" />
        <xs:element name="for" type="Flow" />
        <xs:element name="while" type="Flow" />
        <xs:element name="switch" type="Switch" />
        <xs:element name="bitwise_switch" type="Switch" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="comment" type="xs:string" use="optional" />
    <xs:attribute name="size" type="xs:unsignedInt" use="optional" />
  </xs:complexType>
  <xs:complexType name="Enum">
    <xs:attribute name="display" type="xs:string" use="required" />
    <xs:attribute name="val" type="xs:long" use="optional" />
  </xs:complexType>
  <xs:complexType name="Bit">
    <xs:attribute name="num" type="xs:string" use="required" />
    <xs:attribute name="display" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="BitSet">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="bit" type="Bit" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="MultiValue">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="enum" type="Enum" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="PacketFamily">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="packet" type="Flow" />
    </xs:sequence>
    <xs:attribute name="switchtype" type="xs:string" use="required" />
    <xs:attribute name="way" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="optional" />
  </xs:complexType>
</xs:schema>

=== MoDReD/Packet-Samurai-Versions/PacketSamurai 4.6/dist/protocols/Chat_4.0.x.xml
<?xml version="1.0" encoding="UTF-8"?>
<protocol crypt="Null" checksumSize="3" name="Chat_4.0.x" port="10241"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="protocol.xsd">
	<packetfamilly switchtype="c" way="ServerPackets">
		<packet id="0x31" name="SM_CHAT_INI">
			<part name="unk" type="c" />
			<part name="unk" type="d" />
			<part name="unk" type="h" />
		</packet>
		<packet id="0x02" name="SM_PLAYER_AUTH_RESPONSE">
			<part name="unk(0x40)" type="c" />
			<part name="unk(0x01)" type="h" />
			<part name="unk" type="d" />
			<part name="unk" type="h" />
		</packet>
		<packet id="0x11" name="SM_CHANNEL_RESPONSE">
			<part name="unk(0x40)" type="c" />
			<part name="channelIndex" type="h" />
			<part name="unk(0x00)" type="h" />
			<part name="unk(0x00)" type="h" />
			<part name="channelId" type="d" />
		</packet>
		<packet id="0x1a" name="SM_CHANNEL_MESSAGE">
			<part name="unk(0x00)" type="c" />
			<part name="unk" type="d" />
			<part name="unk" type="d" />
			<part name="channelId" type="d" />
			<part name="clientId" type="d" />
			<part name="unk(0x00)" type="d" />
			<part name="unk(0x00)" type="c" />
			<part name="identifierLength" type="h" id="0" />
			<for id="0">
				<part name="identifier" type="b" size="2" />
			</for>
			<part name="messageLength" type="h" id="1" />
			<for id="1">
				<part name="text" type="b" size="2" />
			</for>
		</packet>
	</packetfamilly>
	<packetfamilly switchtype="c" way="ClientPackets">
		<packet id="0x30" name="CM_CHAT_INI">
			<part name="unk" type="c" />
			<part name="unk" type="h" />
			<part name="unk" type="d" />
			<part name="unk" type="d" />
			<part name="unk" type="d" />
		</packet>
		<packet id="0x05" name="CM_PLAYER_AUTH">
			<part name="AION" type="b" size="29" />
			<part name="playerId" type="d" />
			<part name="unk" type="d" />
			<part name="unk" type="d" />
			<part name="unk" type="d" />
			<part name="length" type="h" id="0" />
			<for id="0">
				<part name="identifier" type="b" size="2" />
			</for>
			<part name="accountLength" type="h" id="1" />
			<for id="1">
				<part name="accountName" type="s" />
			</for>
			<part name="tokenLength" type="h" id="2" />
			<part name="token" type="b" sizeid="2" />
		</packet>
		<packet id="0x10" name="CM_CHANNEL_REQUEST">
			<part name="unk(0x40)" type="c" />
			<part name="unk(0x00)" type="h" />
			<part name="channelIndex" type="h" />
			<part name="unk" type="b" size="18" />
			<part name="length" type="h" id="0" />
			<for id="0">
				<part name="channelIdentifier" type="s" />
			</for>
			<part name="unk" type="d" />
		</packet>
		<packet id="0x18" name="CM_CHANNEL_MESSAGE">
			<part name="unk" type="h" />
			<part name="unk" type="c" />
			<part name="unk" type="d" />
			<part name="unk" type="d" />
			<part name="unk" type="d" />
			<part name="unk" type="d" />
			<part name="channelId" type="d" />
			<part name="unk" type="c" />
			<part name="length" type="h" id="0" />
			<for id="0">
				<part name="content" type="b" size="2" />
			</for>
		</packet>
		<packet id="0x2c" name="UNK">
		</packet>
		<packet id="0xff" name="UNK(PING?)">
			<part name="unk" type="c" />
			<part name="unk" type="h" />
		</packet>
	</packetfamilly>
</protocol>
